"""Pipeline: run every lane in dependency order, then write the run report.

Lanes are isolated: if one raises, the failure is recorded as a warning and the
run continues, so a single broken lane never costs the whole bundle.
"""
from __future__ import annotations

import datetime as _dt
import time
import traceback

from .. import GENERATOR, SCHEMA_VERSION, __version__
from .context import RunContext, artifact_table
from .util import log, write_json, write_text
from .lanes import (inventory, symbols, rag, static_graph, queries, contracts,
                    tests as tests_lane, derived)
from . import rgpacks


def _stage(ctx: RunContext, name: str, fn, *args):
    """Run one lane with timing + error isolation. Returns its result or None."""
    t0 = time.time()
    try:
        result = fn(*args)
    except Exception as e:  # noqa: BLE001 - lane isolation is intentional
        tb = traceback.format_exc(limit=4)
        ctx.warn(f"lane '{name}' failed: {e.__class__.__name__}: {e}")
        log(f"lane '{name}' FAILED:\n{tb}")
        ctx.timings[name] = round(time.time() - t0, 3)
        return None
    ctx.timings[name] = round(time.time() - t0, 3)
    return result


def run(ctx: RunContext) -> None:
    started = _dt.datetime.now().astimezone()
    t0 = time.time()

    # 1. Inventory (foundation; everything downstream consumes its file list).
    inv = _stage(ctx, "inventory", inventory.build, ctx)
    if inv is None:
        ctx.warn("inventory failed; downstream lanes have no file list and are skipped.")
        inv = {"files": [], "git": {}, "coverage": {}}
    ctx.git_meta = inv.get("git", {})

    # 2. Symbols (Python AST -> symbols/imports/occurrences/tags).
    sym = _stage(ctx, "symbols", symbols.build, ctx, inv) or {
        "symbols": [], "imports": [], "routes": [], "modules": {}, "errors": []}

    # 3. Shared ripgrep query packs (used by rag + queries lanes).
    rg_data = _stage(ctx, "rg_packs", rgpacks.run_packs, ctx) or rgpacks.RgData(False)

    # 4. RAG (spans/chunks/bm25/raw-rg/optional vectors).
    _stage(ctx, "rag", rag.build, ctx, inv, sym, rg_data)

    # 5. Static graph (nodes/edges).
    _stage(ctx, "static", static_graph.build, ctx, inv, sym, rg_data)

    # 6. Queries (rg rules+digest, grep-ast previews, semgrep, ast-grep).
    _stage(ctx, "queries", queries.build, ctx, inv, sym, rg_data)

    # 7. Contracts (OpenAPI discovery + route-derived schema).
    _stage(ctx, "contracts", contracts.build, ctx, inv, sym)

    # 8. Tests (pytest collect best-effort + static test-file scan).
    _stage(ctx, "tests", tests_lane.build, ctx, inv, sym)

    # 9. Derived (deterministic summaries — must run last).
    _stage(ctx, "derived", derived.build, ctx, inv, sym, rg_data)

    elapsed = round(time.time() - t0, 3)
    _write_run_metadata(ctx, started, elapsed)
    _write_artifact_guide(ctx, inv, started, elapsed)
    log(f"done in {elapsed}s  ({len(ctx.artifacts)} artifacts, "
        f"{len(ctx.warnings)} warnings)")
    if ctx.warnings:
        log("warnings:")
        for w in ctx.warnings:
            log(f"  - {w}")


def _write_run_metadata(ctx: RunContext, started, elapsed: float) -> None:
    write_json(ctx.paths.run_metadata, {
        "generator": GENERATOR,
        "version": __version__,
        "schema_version": SCHEMA_VERSION,
        "generated_at": started.isoformat(),
        "elapsed_seconds": elapsed,
        "repo_root": ctx.repo,
        "git": ctx.git_meta,
        "tools": ctx.tools.as_dict(),
        "options": vars(ctx.opts),
        "counts": ctx.counts,
        "lane_timings": ctx.timings,
        "warnings": ctx.warnings,
    })


# Recommended reading order for the planning LLM (Phase 2 input list from the plan).
_READING_ORDER = [
    ("ARTIFACT_GUIDE.md", "this file — orientation"),
    ("derived/repo-summary.md", "deterministic human-readable repo overview"),
    ("derived/artifact-index.md", "machine index of every artifact + counts"),
    ("inventory/source-coverage.json", "what was/wasn't covered, language mix"),
    ("symbols/symbols.jsonl", "code-intelligence symbol index"),
    ("rag/chunks.jsonl", "retrieval corpus (paired with rag/bm25.sqlite)"),
    ("static/nodes.jsonl", "graph nodes"),
    ("static/edges.jsonl", "graph edges (imports/calls/inherits/...)"),
    ("queries/results/rg.jsonl", "framework-surface query hits"),
    ("queries/results/grep-ast/", "AST-context previews per surface"),
    ("contracts/openapi.json", "API contract (discovered or route-derived)"),
    ("tests/pytest-collect.txt", "test inventory"),
]


def _write_artifact_guide(ctx, inv, started, elapsed: float) -> None:
    p = ctx.paths
    cov = inv.get("coverage", {})
    git = ctx.git_meta
    L: list[str] = []
    L.append("# Phase 1 Artifact Guide")
    L.append("")
    L.append(f"Generated by **{GENERATOR}** at {started.isoformat()} "
             f"in {elapsed}s.")
    L.append("")
    L.append("This bundle is a deterministic, LLM-free decomposition of a Python "
             "repository into standard / standard-adjacent analysis artifacts. "
             "Later phases (planning, retrieval, writing) consume it.")
    L.append("")

    # Repo identity
    L.append("## Repository")
    L.append("")
    L.append(f"- Root: `{ctx.repo}`")
    if git:
        for k in ("remote", "branch", "head_commit"):
            if git.get(k):
                L.append(f"- {k.replace('_', ' ').title()}: `{git[k]}`")
    L.append(f"- Listing method: `{cov.get('listing_method', 'unknown')}`")
    L.append(f"- Files inventoried: **{cov.get('total_files', 0)}** "
             f"({cov.get('indexable_files', 0)} indexable, "
             f"{cov.get('python_files', 0)} Python)")
    if cov.get("primary_language"):
        L.append(f"- Primary language: **{cov['primary_language']}**")
    L.append("")

    # Tools
    L.append("## Tools used")
    L.append("")
    L.append("| Tool | Status | Detail |")
    L.append("|---|---|---|")
    for t in ctx.tools.all():
        status = "✅ used" if t.available else "⏭️ skipped"
        detail = (t.version or t.note or "").replace("|", "\\|")
        L.append(f"| {t.name} | {status} | {detail} |")
    L.append("")

    # Artifacts by lane
    L.append("## Artifacts")
    L.append("")
    L.append("Each lane writes into its own subdirectory. Counts and the tool that "
             "produced each artifact:")
    L.append("")
    L += artifact_table(ctx.artifacts)
    L.append("")

    # Warnings
    L.append("## Warnings & skipped areas")
    L.append("")
    if ctx.warnings:
        for w in ctx.warnings:
            L.append(f"- {w}")
    else:
        L.append("- None.")
    L.append("")

    # Reading order
    L.append("## Recommended reading order (for the planning LLM)")
    L.append("")
    for i, (path, why) in enumerate(_READING_ORDER, 1):
        L.append(f"{i}. `{path}` — {why}")
    L.append("")
    L.append("> Phase 1 makes no inferences and calls no LLM. Every artifact is a "
             "direct, citeable observation of the repository. Approximate edges in "
             "`static/edges.jsonl` carry a `confidence` field.")
    L.append("")

    write_text(p.artifact_guide, "\n".join(L))
    ctx.record(p.artifact_guide, produced_by="pipeline",
               description="human orientation guide to the bundle")
    ctx.record(p.run_metadata, produced_by="pipeline",
               description="machine-readable run metadata (tools, counts, timings)")
